In [25]:
import numpy as np
import math


In [26]:
A = np.array([1,2,3])
B = np.array([2,4,6])
C = np.array([-1,2])
D = np.array([2,-1])
E = np.array([1,0,2,3,5])
F = np.array([1,4,8,9,11])
G = np.matrix([[1,4],[3,2]])
H = np.matrix([[5,5],[5,5]])

In [38]:
print(A+B)
print(np.cross(A,B))
#print(A-C) no se puede calcular ya que las dimensiones de c y a no son inguales
print(C-D)
print(D.dot(C))
print(E.dot(F))
print(np.linalg.norm(A) + np.linalg.norm(C))
print((np.linalg.norm(E)*np.linalg.norm(F) + np.linalg.norm(C))*A)

m = D.dot(C)
ang = m / (np.linalg.norm(D)*np.linalg.norm(C))
print(math.acos(ang))
print(C*G)
#print(G*C) no se puede calcular 
print(G*np.transpose(np.matrix(C)))


[3 6 9]
[0 0 0]
[-3  3]
-4
99
5.977725364273731
[107.29319529 214.58639059 321.87958588]
2.498091544796509
[[5 0]]
[[7]
 [1]]
